"""
Configuration settings for the data pipeline.
"""

from pathlib import Path


# Directory paths
DATAFOLDER = Path("data")
OUTPUT_FOLDER = Path("")
TRACK_DATA_FOLDER = Path("data")

MIN_POINTS_LAP = 900


# Column names
RELEVANT_COLS = [
    "SESSION_GUID", "M_CURRENTLAPNUM", "M_SESSIONUID", "M_SPEED_1",
    "M_THROTTLE_1", "M_STEER_1", "M_BRAKE_1", "M_GEAR_1", "M_ENGINERPM_1",
    "M_DRS_1", "M_BRAKESTEMPERATURE_RL_1", "M_BRAKESTEMPERATURE_RR_1",
    "M_BRAKESTEMPERATURE_FL_1", "M_BRAKESTEMPERATURE_FR_1",
    "M_TYRESPRESSURE_RL_1", "M_TYRESPRESSURE_RR_1", "M_TYRESPRESSURE_FL_1",
    "M_TYRESPRESSURE_FR_1", "M_CURRENTLAPTIMEINMS_1", "M_LAPDISTANCE_1",
    "M_TOTALDISTANCE_1", "M_CURRENTLAPNUM_1", "M_CURRENTLAPINVALID_1",
    "M_WORLDPOSITIONX_1", "M_WORLDPOSITIONY_1", "M_WORLDPOSITIONZ_1",
    "M_WORLDFORWARDDIRX_1", "M_WORLDFORWARDDIRY_1", "M_WORLDFORWARDDIRZ_1",
    "M_WORLDRIGHTDIRX_1", "M_WORLDRIGHTDIRY_1", "M_WORLDRIGHTDIRZ_1",
    "M_YAW_1", "M_PITCH_1", "M_ROLL_1", "M_FRONTWHEELSANGLE", "M_TRACKID",
    "R_STATUS", "LAPTIME", "CURRENTLAPTIME"
]


# Column renaming dictionary
RENAME_COLS = {
}

# Processing parameters
TRACK_ID = 0
MAX_DISTANCE = 1200
CAR_BUFFER = 0.53
INVALID_DISTANCE_START = 350
INVALID_DISTANCE_END = 600

# Data cleaning
NA_SUBSET_COLS = ["M_WORLDPOSITIONX_1", "M_WORLDPOSITIONY_1"]

FEATURES = [
    'SPEED', 'THROTTLE', 'STEER', 'BRAKE', 'CURRENTLAPTIMEINMS',
    'LAPDISTANCE', 'WORLDPOSITIONX', 'WORLDPOSITIONY',
    'WORLDFORWARDDIRX', 'WORLDFORWARDDIRY', 'YAW', 'PITCH',
    'ROLL', 'left_dist', 'right_dist', 'dist_apex_1', 'dist_apex_2', 'angle_to_apex1',
    'angle_to_apex2', 'proj_from_ref'
]

SET_DISTANCES = [360, 430, 530]
